name: MultiSelect

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Deploy environment name
        type: choice
        required: false
        options:
          - staging
          - production
          - all
        default: all
jobs:
  firstjob:
    runs-on: ubuntu-latest
    name: First Job
    steps:
      - name: Echo
        run: |
          echo "Hello"
          echo "World"
      - name: Set Choice
        run: |
          run: echo "# My Summary Text" >> $GITHUB_STEP_SUMMARY
        
